1. Documentation reading:
A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

2. Create a random tensor with shape (7, 7).

In [27]:
# Import torch
import torch

# Create random tensor
TENSOR_1 = torch.rand(7, 7)
TENSOR_1

tensor([[0.7749, 0.8208, 0.2793, 0.6817, 0.2837, 0.6567, 0.2388],
        [0.7313, 0.6012, 0.3043, 0.2548, 0.6294, 0.9665, 0.7399],
        [0.4517, 0.4757, 0.7842, 0.1525, 0.6662, 0.3343, 0.7893],
        [0.3216, 0.5247, 0.6688, 0.8436, 0.4265, 0.9561, 0.0770],
        [0.4108, 0.0014, 0.5414, 0.6419, 0.2976, 0.7077, 0.4189],
        [0.0655, 0.8839, 0.8083, 0.7528, 0.8988, 0.6839, 0.7658],
        [0.9149, 0.3993, 0.1100, 0.2541, 0.4333, 0.4451, 0.4966]])

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [28]:
# Create another random tensor
TENSOR_2 = torch.rand(1, 7)

# Perform matrix multiplication
torch.matmul(TENSOR_1, TENSOR_2.T)

tensor([[2.1391],
        [2.3548],
        [1.6001],
        [1.9384],
        [1.4356],
        [2.1416],
        [1.7684]])

4. Set the random seed to 0 and do 2 & 3 over again.

In [29]:
# Set manual seed
MANUAL_SEED = torch.manual_seed(seed=0)

# Create two random tensors
T1 = torch.rand(7, 7)
T2 = torch.rand(1, 7)

# Matrix multiply tensors
torch.matmul(T1, T2.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [30]:
# If there is, set the GPU random seed to 1234
# Set random seed on the GPU
GPU_SEED = torch.cuda.manual_seed(1234)

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [31]:
# Set random seed
torch.manual_seed(seed=1234)

# Check for access to GPU
torch.cuda.is_available()
device = "cuda" if torch.cuda.is_available() else "cpu"
device
# Create two random tensors on GPU
random1 = torch.rand(2, 3).to(device)
random2 = torch.rand(2, 3).to(device)
random1, random2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [37]:
# Perform matmul on tensor_A and tensor_B
gpu_mat = torch.matmul(random1, random2.T)
gpu_mat


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

8. Find the maximum and minimum values of the output of 7.

In [33]:
# Find max
MAX = torch.max(gpu_mat)

# Find min
MIN = torch.min(gpu_mat)
MAX, MIN

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

9. Find the maximum and minimum index values of the output of 7.

In [38]:
# Find arg max
ARGMAX = torch.argmax(gpu_mat)

# Find arg min
ARGMIN = torch.argmin(gpu_mat)
ARGMAX, ARGMIN

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [39]:
# Set seed
torch.manual_seed(7)

# Create random tensor
rand_tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
new_tensor = torch.squeeze(rand_tensor)

# Print out tensors and their shapes
print(new_tensor)

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
