In [14]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)

2.1.2+cu121


In [15]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [16]:
scalar.ndim

0

In [17]:
scalar.item()

7

In [18]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [19]:
vector.ndim

1

In [20]:
vector.shape

torch.Size([2])

In [22]:
# Matrix
MATRIX = torch.tensor([[7, 8], 
                      [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [23]:
MATRIX.ndim

2

In [26]:
MATRIX[1]

tensor([ 9, 10])

In [27]:
MATRIX.shape

torch.Size([2, 2])

In [28]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3], 
                        [3, 6, 9], 
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [29]:
TENSOR.ndim

3

In [30]:
TENSOR.shape

torch.Size([1, 3, 3])

In [31]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])